name: CI

on:
  push:
    branches: main
    paths:
      - .github/workflows/ci.yaml
      - lib/**
      - mod.ts
      - discord-irc.ts
      - deno.*
      - README.md
      - TODO.md
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - lib/**
      - mod.ts
      - discord-irc.ts
      - deno.*
      - README.md
      - TODO.md

jobs:
  lint:
    name: Check lint and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check lint
        run: deno lint

      - name: Check format
        run: deno fmt --check

      - name: Check types
        run: |
          deno check discord-irc.ts
          deno check mod.ts
