# This workflow will build the project's Dockerfile and publish images to Docker Hub
# For more information see: https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images

name: Publish Docker image

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: discordirc/discord-irc
          tag_with_ref: true
          tag_with_sha: true
