name: Publish Docker image

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - .github/workflows/ci.yml
      - lib/**
      - deno.json
      - Dockerfile
  release:
    types:
      - published

jobs:
  publish:
    name: Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata for container image
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and publish container image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./docker/Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Compile Windows binary
        run: deno compile -A --target=x86_64-pc-windows-msvc -o discord-irc-windows-x86_64.exe lib/index.ts
      - uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: ./discord-irc-windows-x86_64.exe

      - name: Compile Linux binary
        run: deno compile -A --target=x86_64-unknown-linux-gnu -o discord-irc-linux-x86_64 lib/index.ts && chmod +x discord-irc-linux-x86_64
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64
          path: ./discord-irc-linux-x86_64

      - name: Compile macOS (Intel) binary
        run: deno compile -A --target=x86_64-apple-darwin -o discord-irc-apple-x86_64 lib/index.ts && chmod +x discord-irc-apple-x86_64
      - uses: actions/upload-artifact@v3
        with:
          name: apple-x86_64
          path: ./discord-irc-apple-x86_64

      - name: Compile macOS (Apple Silicon) binary
        run: deno compile -A --target=x86_64-apple-darwin -o discord-irc-apple-arm64 lib/index.ts && chmod +x discord-irc-apple-arm64
      - uses: actions/upload-artifact@v3
        with:
          name: apple-arm64
          path: ./discord-irc-apple-arm64
